platform :ios, '8.0'
inhibit_all_warnings!

target 'ZProject' do

pod 'AFNetworking', '~> 3.0'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'YYKit'
pod 'KVOController'
pod 'MJRefresh'
pod 'MJExtension'
pod 'CYLTabBarController'
pod 'BlocksKit'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'WMPageController'
pod 'LKDBHelper'
end
